### ISSUE TITLE
How its possible?

### ISSUE THREAD

**Issue by dyipon** [nilskohrs/headerblock#1]
Hi,

Im just curious, how your code is removing response headers if the real header/body is generating after all middlewares?

I checked a few another plugin, but they are more complex.

**Comment by nilskohrs** [comment]
There is a difference between header and body. The header is completely known and immutable at the moment the client receives the first bytes. The body however could still be unknown at this point. So after the next.ServeHTTP() has been executed the headers of all middlewares and a potential header response of the underlying service is known and therefor can be edited. As the body is unknown you need to do a lot more work to catch it midflight and resend. This is why it also needs more code to do so.

**Comment by dyipon** [comment]
Thank you!
